### ISSUE TITLE
Add: Wallaby and Quokka

### ISSUE THREAD

**Issue by Noriller** [vitorgalvao/perpetual-fallback-licenses#1]
Both also have a fallback type of license:

- https://wallabyjs.com/docs/intro/license.html#expired-licenses
- https://quokkajs.com/docs/license.html#expired-licenses

**Comment by vitorgalvao** [comment]
Thank you. [Added both](https://github.com/vitorgalvao/perpetual-fallback-licenses/commit/2165be32535398a0d439ba60c4cc76e46b33dc28).
